#!/bin/sh
cd "$(dirname "$0")"

cd Assets
cd Emgu.TF.Lite
mkdir -p Assets
cd Assets
mkdir -p Scripts
cd Scripts

rm -rf Emgu.TF.Util
mkdir -p Emgu.TF.Util
rm -rf Emgu.TF.Lite
mkdir -p Emgu.TF.Lite
rm -rf Emgu.Models
mkdir -p Emgu.Models
rm -rf Emgu.TF.Lite.Models
mkdir -p Emgu.TF.Lite.Models

cd ..
cd ..
cd ..
cd ..

cp ../tensorflow/LICENSE Assets/Emgu.TF.Lite/Documentation/tensorflow.license.txt
#cp unityStoreIcons/README.txt Assets/Emgu.TF/README.txt

cp ../Emgu.TF.Util/*.cs Assets/Emgu.TF.Lite/Assets/Scripts/Emgu.TF.Util/
cp ../Emgu.TF.Lite/*.cs Assets/Emgu.TF.Lite/Assets/Scripts/Emgu.TF.Lite/
cp ../Emgu.Models/*.cs Assets/Emgu.TF.Lite/Assets/Scripts/Emgu.Models/
cp ../Emgu.TF.Lite.Models/*.cs Assets/Emgu.TF.Lite/Assets/Scripts/Emgu.TF.Lite.Models/
