// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: tensorflow/core/protobuf/critical_section.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Tensorflow {

  /// <summary>Holder for reflection information generated from tensorflow/core/protobuf/critical_section.proto</summary>
  public static partial class CriticalSectionReflection {

    #region Descriptor
    /// <summary>File descriptor for tensorflow/core/protobuf/critical_section.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CriticalSectionReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ci90ZW5zb3JmbG93L2NvcmUvcHJvdG9idWYvY3JpdGljYWxfc2VjdGlvbi5w",
            "cm90bxIKdGVuc29yZmxvdyIzChJDcml0aWNhbFNlY3Rpb25EZWYSHQoVY3Jp",
            "dGljYWxfc2VjdGlvbl9uYW1lGAEgASgJImoKG0NyaXRpY2FsU2VjdGlvbkV4",
            "ZWN1dGlvbkRlZhIoCiBleGVjdXRlX2luX2NyaXRpY2FsX3NlY3Rpb25fbmFt",
            "ZRgBIAEoCRIhChlleGNsdXNpdmVfcmVzb3VyY2VfYWNjZXNzGAIgASgIQjYK",
            "GG9yZy50ZW5zb3JmbG93LmZyYW1ld29ya0IVQ3JpdGljYWxTZWN0aW9uUHJv",
            "dG9zUAH4AQFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Tensorflow.CriticalSectionDef), global::Tensorflow.CriticalSectionDef.Parser, new[]{ "CriticalSectionName" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Tensorflow.CriticalSectionExecutionDef), global::Tensorflow.CriticalSectionExecutionDef.Parser, new[]{ "ExecuteInCriticalSectionName", "ExclusiveResourceAccess" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Protocol buffer representing a CriticalSection.
  /// </summary>
  public sealed partial class CriticalSectionDef : pb::IMessage<CriticalSectionDef> {
    private static readonly pb::MessageParser<CriticalSectionDef> _parser = new pb::MessageParser<CriticalSectionDef>(() => new CriticalSectionDef());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CriticalSectionDef> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Tensorflow.CriticalSectionReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CriticalSectionDef() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CriticalSectionDef(CriticalSectionDef other) : this() {
      criticalSectionName_ = other.criticalSectionName_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CriticalSectionDef Clone() {
      return new CriticalSectionDef(this);
    }

    /// <summary>Field number for the "critical_section_name" field.</summary>
    public const int CriticalSectionNameFieldNumber = 1;
    private string criticalSectionName_ = "";
    /// <summary>
    /// Name of the critical section handle.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string CriticalSectionName {
      get { return criticalSectionName_; }
      set {
        criticalSectionName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CriticalSectionDef);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CriticalSectionDef other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CriticalSectionName != other.CriticalSectionName) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (CriticalSectionName.Length != 0) hash ^= CriticalSectionName.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (CriticalSectionName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(CriticalSectionName);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (CriticalSectionName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CriticalSectionName);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CriticalSectionDef other) {
      if (other == null) {
        return;
      }
      if (other.CriticalSectionName.Length != 0) {
        CriticalSectionName = other.CriticalSectionName;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            CriticalSectionName = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// Protocol buffer representing a CriticalSection execution.
  /// </summary>
  public sealed partial class CriticalSectionExecutionDef : pb::IMessage<CriticalSectionExecutionDef> {
    private static readonly pb::MessageParser<CriticalSectionExecutionDef> _parser = new pb::MessageParser<CriticalSectionExecutionDef>(() => new CriticalSectionExecutionDef());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CriticalSectionExecutionDef> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Tensorflow.CriticalSectionReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CriticalSectionExecutionDef() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CriticalSectionExecutionDef(CriticalSectionExecutionDef other) : this() {
      executeInCriticalSectionName_ = other.executeInCriticalSectionName_;
      exclusiveResourceAccess_ = other.exclusiveResourceAccess_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CriticalSectionExecutionDef Clone() {
      return new CriticalSectionExecutionDef(this);
    }

    /// <summary>Field number for the "execute_in_critical_section_name" field.</summary>
    public const int ExecuteInCriticalSectionNameFieldNumber = 1;
    private string executeInCriticalSectionName_ = "";
    /// <summary>
    /// Name of the critical section handle.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ExecuteInCriticalSectionName {
      get { return executeInCriticalSectionName_; }
      set {
        executeInCriticalSectionName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "exclusive_resource_access" field.</summary>
    public const int ExclusiveResourceAccessFieldNumber = 2;
    private bool exclusiveResourceAccess_;
    /// <summary>
    /// Whether this operation requires exclusive access to its resources,
    /// (i.e., no other CriticalSections may request the same resources).
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool ExclusiveResourceAccess {
      get { return exclusiveResourceAccess_; }
      set {
        exclusiveResourceAccess_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CriticalSectionExecutionDef);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CriticalSectionExecutionDef other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ExecuteInCriticalSectionName != other.ExecuteInCriticalSectionName) return false;
      if (ExclusiveResourceAccess != other.ExclusiveResourceAccess) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ExecuteInCriticalSectionName.Length != 0) hash ^= ExecuteInCriticalSectionName.GetHashCode();
      if (ExclusiveResourceAccess != false) hash ^= ExclusiveResourceAccess.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ExecuteInCriticalSectionName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ExecuteInCriticalSectionName);
      }
      if (ExclusiveResourceAccess != false) {
        output.WriteRawTag(16);
        output.WriteBool(ExclusiveResourceAccess);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ExecuteInCriticalSectionName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ExecuteInCriticalSectionName);
      }
      if (ExclusiveResourceAccess != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CriticalSectionExecutionDef other) {
      if (other == null) {
        return;
      }
      if (other.ExecuteInCriticalSectionName.Length != 0) {
        ExecuteInCriticalSectionName = other.ExecuteInCriticalSectionName;
      }
      if (other.ExclusiveResourceAccess != false) {
        ExclusiveResourceAccess = other.ExclusiveResourceAccess;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ExecuteInCriticalSectionName = input.ReadString();
            break;
          }
          case 16: {
            ExclusiveResourceAccess = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
