// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/framework/types.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Tensorflow {

  /// <summary>Holder for reflection information generated from tensorflow/core/framework/types.proto</summary>
  public static partial class TypesReflection {

    #region Descriptor
    /// <summary>File descriptor for tensorflow/core/framework/types.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TypesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiV0ZW5zb3JmbG93L2NvcmUvZnJhbWV3b3JrL3R5cGVzLnByb3RvEgp0ZW5z",
            "b3JmbG93KsIFCghEYXRhVHlwZRIOCgpEVF9JTlZBTElEEAASDAoIRFRfRkxP",
            "QVQQARINCglEVF9ET1VCTEUQAhIMCghEVF9JTlQzMhADEgwKCERUX1VJTlQ4",
            "EAQSDAoIRFRfSU5UMTYQBRILCgdEVF9JTlQ4EAYSDQoJRFRfU1RSSU5HEAcS",
            "EAoMRFRfQ09NUExFWDY0EAgSDAoIRFRfSU5UNjQQCRILCgdEVF9CT09MEAoS",
            "DAoIRFRfUUlOVDgQCxINCglEVF9RVUlOVDgQDBINCglEVF9RSU5UMzIQDRIP",
            "CgtEVF9CRkxPQVQxNhAOEg0KCURUX1FJTlQxNhAPEg4KCkRUX1FVSU5UMTYQ",
            "EBINCglEVF9VSU5UMTYQERIRCg1EVF9DT01QTEVYMTI4EBISCwoHRFRfSEFM",
            "RhATEg8KC0RUX1JFU09VUkNFEBQSEAoMRFRfRkxPQVRfUkVGEGUSEQoNRFRf",
            "RE9VQkxFX1JFRhBmEhAKDERUX0lOVDMyX1JFRhBnEhAKDERUX1VJTlQ4X1JF",
            "RhBoEhAKDERUX0lOVDE2X1JFRhBpEg8KC0RUX0lOVDhfUkVGEGoSEQoNRFRf",
            "U1RSSU5HX1JFRhBrEhQKEERUX0NPTVBMRVg2NF9SRUYQbBIQCgxEVF9JTlQ2",
            "NF9SRUYQbRIPCgtEVF9CT09MX1JFRhBuEhAKDERUX1FJTlQ4X1JFRhBvEhEK",
            "DURUX1FVSU5UOF9SRUYQcBIRCg1EVF9RSU5UMzJfUkVGEHESEwoPRFRfQkZM",
            "T0FUMTZfUkVGEHISEQoNRFRfUUlOVDE2X1JFRhBzEhIKDkRUX1FVSU5UMTZf",
            "UkVGEHQSEQoNRFRfVUlOVDE2X1JFRhB1EhUKEURUX0NPTVBMRVgxMjhfUkVG",
            "EHYSDwoLRFRfSEFMRl9SRUYQdxITCg9EVF9SRVNPVVJDRV9SRUYQeEIsChhv",
            "cmcudGVuc29yZmxvdy5mcmFtZXdvcmtCC1R5cGVzUHJvdG9zUAH4AQFiBnBy",
            "b3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Tensorflow.DataType), }, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// LINT.IfChange
  /// </summary>
  public enum DataType {
    /// <summary>
    /// Not a legal value for DataType.  Used to indicate a DataType field
    /// has not been set.
    /// </summary>
    [pbr::OriginalName("DT_INVALID")] DtInvalid = 0,
    /// <summary>
    /// Data types that all computation devices are expected to be
    /// capable to support.
    /// </summary>
    [pbr::OriginalName("DT_FLOAT")] DtFloat = 1,
    [pbr::OriginalName("DT_DOUBLE")] DtDouble = 2,
    [pbr::OriginalName("DT_INT32")] DtInt32 = 3,
    [pbr::OriginalName("DT_UINT8")] DtUint8 = 4,
    [pbr::OriginalName("DT_INT16")] DtInt16 = 5,
    [pbr::OriginalName("DT_INT8")] DtInt8 = 6,
    [pbr::OriginalName("DT_STRING")] DtString = 7,
    /// <summary>
    /// Single-precision complex
    /// </summary>
    [pbr::OriginalName("DT_COMPLEX64")] DtComplex64 = 8,
    [pbr::OriginalName("DT_INT64")] DtInt64 = 9,
    [pbr::OriginalName("DT_BOOL")] DtBool = 10,
    /// <summary>
    /// Quantized int8
    /// </summary>
    [pbr::OriginalName("DT_QINT8")] DtQint8 = 11,
    /// <summary>
    /// Quantized uint8
    /// </summary>
    [pbr::OriginalName("DT_QUINT8")] DtQuint8 = 12,
    /// <summary>
    /// Quantized int32
    /// </summary>
    [pbr::OriginalName("DT_QINT32")] DtQint32 = 13,
    /// <summary>
    /// Float32 truncated to 16 bits.  Only for cast ops.
    /// </summary>
    [pbr::OriginalName("DT_BFLOAT16")] DtBfloat16 = 14,
    /// <summary>
    /// Quantized int16
    /// </summary>
    [pbr::OriginalName("DT_QINT16")] DtQint16 = 15,
    /// <summary>
    /// Quantized uint16
    /// </summary>
    [pbr::OriginalName("DT_QUINT16")] DtQuint16 = 16,
    [pbr::OriginalName("DT_UINT16")] DtUint16 = 17,
    /// <summary>
    /// Double-precision complex
    /// </summary>
    [pbr::OriginalName("DT_COMPLEX128")] DtComplex128 = 18,
    [pbr::OriginalName("DT_HALF")] DtHalf = 19,
    [pbr::OriginalName("DT_RESOURCE")] DtResource = 20,
    /// <summary>
    /// Do not use!  These are only for parameters.  Every enum above
    /// should have a corresponding value below (verified by types_test).
    /// </summary>
    [pbr::OriginalName("DT_FLOAT_REF")] DtFloatRef = 101,
    [pbr::OriginalName("DT_DOUBLE_REF")] DtDoubleRef = 102,
    [pbr::OriginalName("DT_INT32_REF")] DtInt32Ref = 103,
    [pbr::OriginalName("DT_UINT8_REF")] DtUint8Ref = 104,
    [pbr::OriginalName("DT_INT16_REF")] DtInt16Ref = 105,
    [pbr::OriginalName("DT_INT8_REF")] DtInt8Ref = 106,
    [pbr::OriginalName("DT_STRING_REF")] DtStringRef = 107,
    [pbr::OriginalName("DT_COMPLEX64_REF")] DtComplex64Ref = 108,
    [pbr::OriginalName("DT_INT64_REF")] DtInt64Ref = 109,
    [pbr::OriginalName("DT_BOOL_REF")] DtBoolRef = 110,
    [pbr::OriginalName("DT_QINT8_REF")] DtQint8Ref = 111,
    [pbr::OriginalName("DT_QUINT8_REF")] DtQuint8Ref = 112,
    [pbr::OriginalName("DT_QINT32_REF")] DtQint32Ref = 113,
    [pbr::OriginalName("DT_BFLOAT16_REF")] DtBfloat16Ref = 114,
    [pbr::OriginalName("DT_QINT16_REF")] DtQint16Ref = 115,
    [pbr::OriginalName("DT_QUINT16_REF")] DtQuint16Ref = 116,
    [pbr::OriginalName("DT_UINT16_REF")] DtUint16Ref = 117,
    [pbr::OriginalName("DT_COMPLEX128_REF")] DtComplex128Ref = 118,
    [pbr::OriginalName("DT_HALF_REF")] DtHalfRef = 119,
    [pbr::OriginalName("DT_RESOURCE_REF")] DtResourceRef = 120,
  }

  #endregion

}

#endregion Designer generated code
