#!/bin/sh
cd "$(dirname "$0")"

convert ../tensorflow/tensorflow/examples/multibox_detector/data/surfers.jpg Assets/Emgu.TF/Demo/Resources/surfers.png
convert ../Emgu.TF.Example/XamarinForms/XamarinForms/space_shuttle.jpg Assets/Emgu.TF/Demo/Resources/space_shuttle.png
cp unityStoreIcons/EmguTFLogo_128x128.png Assets/Emgu.TF/Demo/EmguTFLogo.png