#!/bin/sh
cd "$(dirname "$0")"

cp Assets/Emgu.TF/Assets/Scripts/Emgu.TF.Util/*.cs ../Emgu.TF.Util/
cp Assets/Emgu.TF/Assets/Scripts/Emgu.TF/*.cs ../Emgu.TF/
cp Assets/Emgu.TF/Assets/Scripts/Emgu.TF.Models/*.cs ../Emgu.TF.Models/
cp Assets/Emgu.TF/Assets/Scripts/Emgu.Models/*.cs ../Emgu.Models/

